# Task 4: Most Preferred Investment Avenue

## Identify the most preferred investment avenue

In [ ]:
import pandas as pd
file_path = "Data_set 2 - Copy.csv"
df = pd.read_csv(file_path)

In [15]:
Analyze_column = df[['Mutual_Funds', 'Equity_Market', 'Debentures', 'Government_Bonds', 'Fixed_Deposits', 'PPF', 'Gold']]

In [16]:
Analyze_column

,Mutual_Funds,Equity_Market,Debentures,Government_Bonds,Fixed_Deposits,PPF,Gold
0,1,2,5,3,7,6,4
1,4,3,2,1,5,6,7
2,3,6,4,2,5,1,7
3,2,1,3,7,6,4,5
4,2,1,3,6,4,5,7
5,7,5,4,6,3,1,2
6,3,6,4,2,5,1,7
7,2,3,7,4,6,1,5
8,2,4,7,5,3,1,6
9,1,3,7,4,5,2,6
10,2,4,7,5,3,1,6
11,2,5,7,6,3,1,4
12,1,2,3,4,5,6,7
13,2,3,7,4,5,1,6
14,2,3,7,5,4,1,6
15,2,3,7,5,4,1,6
16,3,2,7,5,4,1,6
17,3,2,7,4,5,1,6
18,3,2,7,4,5,1,6
19,3,4,6,5,1,2,7
20,2,4,7,5,3,1,6
21,2,4,5,6,3,1,7
22,3,4,6,5,2,1,7
23,2,4,6,5,3,1,7
24,2,3,7,5,4,1,6
25,3,4,7,5,1,2,6
26,3,4,6,5,1,2,7
27,2,3,7,6,4,1,5
28,2,3,6,5,1,4,7
29,5,4,3,2,7,1,6
30,4,5,1,2,7,3,6
31,2,4,7,6,3,1,5
32,2,4,7,5,1,3,6
33,2,3,6,4,1,5,7
34,2,3,6,5,4,1,7
35,1,4,6,5,3,2,7
36,2,4,7,5,1,3,6
37,5,4,7,6,1,2,3
38,2,4,7,5,3,1,6
39,4,3,5,7,2,1,6

In [17]:
for column in Analyze_column.columns:
    frequency = df[column].value_counts()
    
    # Get the most frequent value and its count
    most_frequent_value = frequency.idxmax()
    highest_frequency = frequency.max()
    
    print(f"Column: {column}")
    print(f"Most frequent value: {most_frequent_value}, Frequency: {highest_frequency}")
    print('-' * 50)

Column: Mutual_Funds
Most frequent value: 2, Frequency: 21
--------------------------------------------------
Column: Equity_Market
Most frequent value: 4, Frequency: 16
--------------------------------------------------
Column: Debentures
Most frequent value: 7, Frequency: 20
--------------------------------------------------
Column: Government_Bonds
Most frequent value: 5, Frequency: 18
--------------------------------------------------
Column: Fixed_Deposits
Most frequent value: 3, Frequency: 10
--------------------------------------------------
Column: PPF
Most frequent value: 1, Frequency: 24
--------------------------------------------------
Column: Gold
Most frequent value: 6, Frequency: 18
--------------------------------------------------